ForApp/Models/Cart.cs
using ForApp.Areas.Identity.Data;
using System.ComponentModel.DataAnnotations.Schema;

namespace ForApp.Models
{
    public class Cart
    {
        public string UId { get; set; }
        public string BookIsbn { get; set; }
        public int Quantity { get; set; }
        public AppUser? User { get; set; }
        public Book? Book { get; set; }
    }
}

ForApp/Controllers/CartsController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ForApp.Data;
using ForApp.Models;
using ForApp.Areas.Identity.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace ForApp.Controllers
{
    public class CartsController : Controller
    {
        private readonly UserContext _context;
        private readonly UserManager<AppUser> _userManager;

        public CartsController(UserContext context, UserManager<AppUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        [HttpPost]
        [Authorize(Roles = "Customer")]
        public async Task<IActionResult> Update(Cart cart)
        {

            if (ModelState.IsValid)
            {
                _context.Cart.Update(cart);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction("Index");
        }
    
    // GET: Carts
    [Authorize(Roles = "Customer")]
        public ActionResult Index()
        {
            string thisUserId = _userManager.GetUserId(HttpContext.User);
            var cart = _context.Cart
                .Include(x => x.Book)
                .Include(x => x.User)
                .Where(c => c.UId == thisUserId).ToList();
            return View(cart);
        }
    [Authorize(Roles = "Customer")]
        public async Task<IActionResult> Remove(string isbn)
        {
            string thisUserId = _userManager.GetUserId(HttpContext.User);
            Cart fromDb = _context.Cart.FirstOrDefault(c => c.UId == thisUserId && c.BookIsbn == isbn);
            _context.Remove(fromDb);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

ForApp/Controllers/OrdersController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ForApp.Data;
using ForApp.Models;
using Microsoft.AspNetCore.Identity;
using ForApp.Areas.Identity.Data;
using Microsoft.AspNetCore.Authorization;

namespace ForApp.Controllers
{
    public class OrdersController : Controller
    {
        private readonly UserContext _context;
        private readonly UserManager<AppUser> _userManager;

        public OrdersController(UserContext context, UserManager<AppUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }
        // GET: Orders
        //list order for seller
        public async Task<IActionResult> Index()
		{
			var orderContext = _context.Order.Include(o => o.User);
			return View(await orderContext.ToListAsync());
		}
        /*        public async Task<IActionResult> Index(Order order)
				{
					var thisUserId = _userManager.GetUserId(HttpContext.User);
					Store thisStore = await _context.Store.FirstOrDefaultAsync(s => s.UId == thisUserId);
					order.UId = thisStore.UId;
					var userContext = _context.Order.Include(o => o.User);
					return View(_context.Order.Where(c => c.UId == thisUserId));
				}*/

        //order history for customer
        [Authorize(Roles = "Customer")]
        public async Task<IActionResult> OrderHistory()
        {
            var userContext = _context.Order.Include(o => o.User);
            string thisUserId = _userManager.GetUserId(HttpContext.User);
            return View(_context.Order.Where(c => c.UId == thisUserId));
        }
        // GET: Orders/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Order
                .Include(o => o.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }
        private bool OrderExists(int id)
        {
            return _context.Order.Any(e => e.Id == id);
        }
    }
}

ForApp/Views/Carts/Index.cshtml
@model IEnumerable<ForApp.Models.Cart>
@{
	ViewData["Title"] = "Cart";
}

<h1>Check Your Cart</h1>
<p>
	<a asp-controller="Orders" asp-action="OrderHistory">List Order</a>
</p>

<table class="table">
	<thead>
		<tr>
			<th>
				@Html.DisplayNameFor(model => model.BookIsbn)
			</th>
			<th>
				Title
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Quantity)
			</th>
			<th>
				Total
			</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		@foreach (var item in Model)
		{
			<tr>
				<td>
					@Html.DisplayFor(modelItem => item.BookIsbn)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Book.Title)
				</td>
				<td>
					 <form method="post" asp-controller="Carts" asp-action="Update">
                                <input hidden name="UId" asp-for="@item.UId">
                                <input hidden name="BookIsbn" asp-for="@item.BookIsbn">         
                                <input id="quantity" id="quantity" min="1" name="quantity"  asp-for="@item.Quantity" type="number">                  
                                <div><input type="submit" value="Update" class="btn btn-primary btn-sm"/></div>
                     </form>
				</td>
				<td>
					<span class='table-sub-total'>@(item.Book.Price * item.Quantity)</span>
				</td>
				<td>
					<a asp-action="Remove" asp-route-isbn="@item.BookIsbn" class="btn btn-danger">Remove</a>
				</td>
			</tr>
		}
	</tbody>
</table>
<a asp-controller="Books" asp-action="Checkout" class="btn btn-primary btn-lg btn-block">Checkout</a>