ForApp/Models/Order.cs
using ForApp.Areas.Identity.Data;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ForApp.Models
{
    public class Order
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Display(Name = "OrderID")]
        public int Id { get; set; }
        public string UId { get; set; }
        public DateTime OrderDate { get; set; }
        public double Total { get; set; }
        public AppUser User { get; set; }
        public virtual ICollection<OrderDetail>? OrderDetails { get; set; }
    }

}

ForApp/Controllers/OrderDetailsController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ForApp.Data;
using ForApp.Models;

namespace ForApp.Controllers
{
    public class OrderDetailsController : Controller
    {
        private readonly UserContext _context;

        public OrderDetailsController(UserContext context)
        {
            _context = context;
        }

        // GET: OrderDetails
        public async Task<IActionResult> Index()
        {
            var orderContext = _context.OrderDetail.Include(o => o.Book).Include(o => o.Order);
            return View(await orderContext.ToListAsync());
        }
        public async Task<IActionResult> Detail(int id)
        {
            var orderContexts = _context.OrderDetail.Where(c => c.OrderId == id).Include(o => o.Book).Include(o => o.Order);
            return View(await orderContexts.ToListAsync());
        }
        private bool OrderDetailExists(int id)
        {
            return _context.OrderDetail.Any(e => e.OrderId == id);
        }
    }
}

ForApp/Controllers/OrdersController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ForApp.Data;
using ForApp.Models;
using Microsoft.AspNetCore.Identity;
using ForApp.Areas.Identity.Data;
using Microsoft.AspNetCore.Authorization;

namespace ForApp.Controllers
{
    public class OrdersController : Controller
    {
        private readonly UserContext _context;
        private readonly UserManager<AppUser> _userManager;

        public OrdersController(UserContext context, UserManager<AppUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }
        // GET: Orders
        //list order for seller
        public async Task<IActionResult> Index()
		{
			var orderContext = _context.Order.Include(o => o.User);
			return View(await orderContext.ToListAsync());
		}
        /*        public async Task<IActionResult> Index(Order order)
				{
					var thisUserId = _userManager.GetUserId(HttpContext.User);
					Store thisStore = await _context.Store.FirstOrDefaultAsync(s => s.UId == thisUserId);
					order.UId = thisStore.UId;
					var userContext = _context.Order.Include(o => o.User);
					return View(_context.Order.Where(c => c.UId == thisUserId));
				}*/

        //order history for customer
        [Authorize(Roles = "Customer")]
        public async Task<IActionResult> OrderHistory()
        {
            var userContext = _context.Order.Include(o => o.User);
            string thisUserId = _userManager.GetUserId(HttpContext.User);
            return View(_context.Order.Where(c => c.UId == thisUserId));
        }
        // GET: Orders/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Order
                .Include(o => o.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }
        private bool OrderExists(int id)
        {
            return _context.Order.Any(e => e.Id == id);
        }
    }
}

ForApp/Views/Orders/Index.cshtml
@model IEnumerable<ForApp.Models.Order>

@{
    ViewData["Title"] = "Order History";
}

<h1>Order History for Seller</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.OrderDate)
            </th>
            <th>
                Customer
            </th>
            <th>
                @Html.DisplayNameFor(model => model.User.Address)
            </th>
             <th>
                @Html.DisplayNameFor(model => model.Total)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OrderDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.User.UserName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.User.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Total)
            </td>
            <td>
                <a asp-controller="OrderDetails" asp-action="Detail" asp-route-id="@item.Id">Details</a>
            </td>
        </tr>
}
    </tbody>
</table>

ForApp/Views/Orders/OrderHistory.cshtml
@model IEnumerable<ForApp.Models.Order>

@{
    ViewData["Title"] = "Order History";
}

<h1>Order History for Customer</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.OrderDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Total)
            </th>
            <th>
                Action
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OrderDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Total)
            </td>
            <td>
                <a asp-controller="OrderDetails" asp-action="Detail" asp-route-id="@item.Id">Details</a>
            </td>
        </tr>
}
    </tbody>
</table>